server:
  tomcat:
    basedir: ./logs/newblog

spring:
  config:
    import: classpath:application-common.yml
  datasource:
    url: jdbc:mysql://43.153.15.174:3306/myblog?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ZtO1tkJMVV
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 43.153.15.174:
    password: 0CVF5Dsh79
    port: 31857

management:
  metrics:
    export:
      elastic:
        host: http://es.wenzhihuai.com
        user-name: elastic
        password: elastic-admin
        index-date-format: yyyy-MM-dd